services:
  nestjs_api_prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3001:3001'
    environment:
      - ports=3001
      - NODE_ENV=production
    volumes:
      - ./src:/app/src

  mysql_db:
    image: mysql
    # ports:
    # - '3307:3307'
    environment:
    - MYSQL_ROOT_PASSWORD=root_password_123
    - MYSQL_DATABASE=nestjs_docker
    - MYSQL_USER=testuser
    - MYSQL_PASSWORD=testuser123
    - MYSQL_TCP_PORT=3307